var KatanaZero = "<h2>Katana Zero</h2> <img src='imagens/begging.jpg' />  <p>Em uma cidade escura e chuvosa, em um mundo controlado pelo governo e dominado de guerras, o governo desenvolveu uma droga, uma droga capaz de ser autoaprimorar e utilizaram pra desenvolver um exército para dominar terras e consquistar o planeta. E assim acorda o Zero, um robô muito semelhante a um humano e com a marca do exercíto, com o braço enferrujado e com peças faltando, Zero acorda perto de um posto de gasolina abandonado, ele não se lembra de nada apenas de seu nome, ao seu lado a sua katana escrita com seu nome, Zero percebe que está danificado e sem carga assim lembra que é um robô procurado pelo governo. Zero vai até o posto e encontra algumas peças antigas de robô e uma bateria antiga, fora do modelo avançado do seu corpo, ao ver as peças e se lembra do seu antigo amigo de guerra, o Nier, um amigo robô na qual foi desenvolvido junto com ele, Zero deseja encontra Nier para sabe sobre seu passado obscuro. Zero começa a se autoconsertar com as peças antigas e deseja muito atrás do Nier e vai em buscar de respostas na cidade mais próxima..</p> <button onclick='carregarConteudo(EmBuscaDeNier)'>Ir em buscar de Nier</button> <button onclick='carregarConteudo(Bar)'>Ir para o bar</button>";

var Bar = "<img src='imagens/bar.jpg' /> <h2>Bar</h2> <p>Zero não está muito afim de saber o que aconteceu nem sobre o que está acontecendo, ele apenas notou que tem alguns trocados no balcão do posto e decide ir tomar breja, afinal ele é apenas um robô sem memória e com peças velhas, por que não ir para um bar? Pois então é isso que Zero fez, ele partiu deixando seu passado para trás, após algumas horas finalmente achou um bar, usou seus trocados e bebeu até se descarregar, acho que a bateria que ele encontrou não estava tão carregada assim...</p> <button onclick='carregarConteudo(KatanaZero)'>Tente novamente</button>";

var EmBuscaDeNier = "<img src='imagens/city.jpg' /> <h2>Cidade</h2>  <p>Zero caminha por horas até chega na cidade, onde sobe um grande prédio e encontra um gato preto e meio magro, já é de noite, as ruas estão vazias Zero observa os cartezes de diversos robôs procurados, entre eles, havia Zero e Nier, Zero leva o cartaz e vai até o armazem secretos dos robôs. Ao chegar próximo do armazem de robôs, ele já nota o excesso de óleo nas ruas e nas paredes, marcas de mão e pés, tudo em um formato semelhante as da técnologia dele, Zero entra no armazem e encontra diversos robôs do esquadrão dele mortos, estrasalhados e decapitados, Quem fez isso, disse Zero com enjoo e espantado, ele escuta uma voz, é o Nier, ele está sem suas pernas e com uma katana escrito Dragão no peito pendurando o Nier na parede dos fundos, Zero está assustado, o esquadrão mais forte está todo morto, disse Zero, nier enquanto estava perdendo sua consciência disse : Aonde você estava Zero, Zero conta que não se lembra de nada e que acordou no meio do nada, Nier começa a explicar, O governo desenvolver um esquadrão poderoso para eliminar todos os robôs, eles são chamados de Dragões, eles são poderosos e utilizaram a droga como nós, Zero pergunta sobre a droga, Nier conta que os robôs foram um projeto do governo com a utilização das drogas pra derrotamos outros países, porém foi um fracasso, e agora querem  eliminar todos os robôs, talvez você seja o último disse Nier para o Zero, ao disse isso Nier se despedi de Zero e aponta para a porta dos fundos, onde há os registros de todos os abrigos robóticos, equipamentos e a localização do criador dos robôs. Zero pensa em duas alternativas, ir atrás do criador ou se aprimorar para enfrentar os Dragões. </p> <button onclick='carregarConteudo(Criador)'>Ir atrás do criador</button> <button onclick='carregarConteudo(Aprimorar)'>Ir até os Dragões</button>";

var Criador = "<img src='imagens/fuga.jpg' />  <h2>Criador</h2> <p>Zero deseja ir atrás de respostas, então ele vasculha os documentos e achar um mapa onde exatamente está o criador dos robôs, Zero passa mais uma vez pela cena de seus compainheiros mortos e segue a porta da frente, ver seus companheiros mortos e sentir aquele cheiro o abalou, ele pode ser um robô porém, ele ainda sente sentimentos pelos seus colegas antes de ir a porta, ele grava a sua katana no chão e jura aos colegas mortos que trará a vingança a todos, de joelhos Zero foca na cena tenta adquirir seu poder de volta mas a droga já não está mais causando enfeitos, ele precisa se recarregar. Zero pega sua katana do chão e vai a saída e encontra vários carros e polícias cercando de todos os lados, o governo o achou, nos prédios há três guerreios com katanas e simbolos de dragões na roupa, um deles está cheio de óleo, a polícia solicitar que jogue a arma no chão, Zero está irritado e começa a matar os polícias, um deles acerta ele, você ja era, diz um dos Dragões, mesmo ferido zero derrubar todos os polícias porém ao matar o último guarda, um dragão o acerta no peito, você foi o mais fraco, disse o dragão que estava com as roupa cheia de óleo, eu matei seus amigos e agora você se unirar com eles. Zero está morto </p> <button onclick='carregarConteudo(KatanaZero)'>Tente de novo</button>";

var Aprimorar = "<img src='imagens/poderes.jpg' />  <h2>Aprimoramentos</h2> <p>Zero vasculha a sala inteira, ele encontra peças do modelo mais avançado que há, dentro de uma caixa que havia as peças ele acha uma recarrega grande da droga do governo, com isso poderei recuperar meus poderes disse Zero, ele fica de joelho e concentra todo o seu corpo para lembrar de seus poderes, assim eu recupera seu auto reflexo, deixando capaz de refletir alguns projéteis, em uma das caixas havia uma chave escrito fundo nela, é a chave dos fundo, disse o Zero, então lá foi ele ao fundos. Indo aos fundos alguns polícias que estavam aguardando ele na porta começaram a entrar, Zero sacou sua katana e começaram os disparos, Zero ativou seu reflexo e viu aquela oportunidade como uma ótima forma para treinar e foi para cima dos guardas, refletia suas balas como nunca, conseguia ver todos os trajetos e anglos, eliminou todos, mas sabia que mais guardas iriam vim, foi depressa a porta dos fundos, chegando lá encontrou uma porta enorme de ferro, parecia um bunker, utilizou a chave com delicadeza para não quebrar a chave, ABRIU ele disse, entrou correndo e fechou a porta, em seguida ouviu uma voz dizendo finalmente você apareceu, Zero olhou para trás e viu que quem estava lá na frente dele era ninguém menos que seu criador. Ele explica que o esquadrão que está morto lá na frente morreram protegendo ele, e diz que os dragões roubaram a fórmula da droga e estão fabricando e fazendo soldados para eles mesmo, aqueles não são polícias, são recrutas dos dragões, diz o criador. Enquanto isso os dragões estão tentando quebrar a porta,o criador quer que você corra pra longe, Zero tem duas escolhas ficar e tentar proteger ou correr </p> <button onclick='carregarConteudo(Correr)'>Correr</button> <button onclick='carregarConteudo(Proteger)'>Proteger</button>";

var Proteger = "<img src='imagens/lab.png' />  <h2>Proteger</h2> <p> Zero decide proteger seu criador, após tanto tempo sem achar seu mestre, quando finalmente o encontra partir assim? juntos eles criam uma barreira na porta para ganhar tempo, com isso eles vão a porta dos fundos, precisamos achar um local seguro disse Zero ao criador, eles vão por cimas do prédios atrás de um abrigo longe do alcance dos dragões. Após um longo tempo acham uma sala bem longe do centro da cidade em um antigo quarto do criador, é aqui o local, disse o criador, então o mestre começa a explicar que o dragões dominaram o governo e decidiram matar todos quem ligação com os robôs, com isso Zero já estava com a bateria descarregando, então o criador colocou ele em uma capsula para carregar e fazer alguns ajustes finais no corpo de Zero. Um dia se passou, Zero acorda e está se sentido como nunca se sentiu antes, mais rápido, mais forte, mais leve. Fiz bem em proteger você, disse o Zero ao criador, agora só falta uma coisa uma katana aprimorada, os dragões são fortes porém tem pontos fracos, todos podem facilmente ser derrotados com a Phoenix Edge, uma katana especial criada por um antigo mestre do corte, e guardada bem no centro da cidade. Zero tem duas escolhas enfrentar os dragões ou ir em busca da katana</p> <button onclick='carregarConteudo(dragões)'>Enfrentar os dragões</button> <button onclick='carregarConteudo(espadas)'>Ir em busca da katana</button>";

var Correr = "<img src='imagens/run.png' />  <h2>Correr</h2> <p>Correr as vezes pode não ser a melhor escolha, mas talvez nesse sentido pode ser a melhor alternativa, Zero corre para as portas do fundo e enquanto, correr escuta os gritos de seu criador sendo cortado diversas vezes pelos dragões, agora sem rumo Zero está vagando por informações, ele se questiona diversas vezes, será que há outro robô ainda ? será que há alguém querendo derrubar o governo? por que o governo quer destruiu algo que eles criaram ? vagando pela ruas, entrou em um bar em um bairro bem obscuro, havia uma mulher com uma katana e uma roupa azul, ela se aproxima do Zero e diz sussurando: finalmente apareceu estava tentando falar com você a dias, Zero confuso apenas diz sussurando: Quem é você? Eu perdi minha memória eu acordei no meio do nada, Então ela o convida para uma mesa e conta sobre a relação deles, somos uma equipe formada pelos sobreviventes da guerra, os Kibuzi, meu codinome é Snow disse ela. Zero começa a lembrar do grande esquadrão que ele havia formado, como pude esquecer dos Kibuzi, passam o dia conversando e vão pelas sombras até o abrigo. Kibuzi são no total 4 membros e usuários da de katanas, eles buscam destruir os dragões e também são guerreios que utilizam a droga. Zero aproveita para utilizar mais da droga e foca a voltar suas habilidades, com isso sua percepção e campo de visão aumentam. Os kibuzi sugerem pegar umas das 5 gold katanas, pois são katanas poderosas e cada uma com uma habilidade diferente. Agora você decide, Ir atrás dos dragões ou Ir em busca das espadas</p> <button onclick='carregarConteudo(espadas1)'>Ir em busca das katanas</button> <button onclick='carregarConteudo(dragões)'>Ir atrás dos dragões</button>";

var espadas = "<img src='imagens/espadas.png' /> <h2>Katanas/h2> <p>Então Zero decide que é melhor ir atrás das katanas, a localização não era muito longe da sua localização atual, utilizando seu novo corpo, Zero acha a localização e parti ao anoitecer, chegando lá você depara com diversos guardas na entrada, mas Zero está lidando está situação com uma facilidade é como se estiver cortando folhas e repelindo todas os projéteis, nada o atingia, chegando perto das espadas ele encontrou dois dos três dragões, sabiamos que estaria aqui disse um, você ira morrer aqui disse o outro, a sua frente há uma luta díficil um contra dois, porém nada além do seu nível, não há formas de correr ou se proteger, então você vai a frente no combate, os dois dragões te acompanham, Zero esquiva de vários golpes mas ainda sim é atingido, uma batalha de agilidade e força pelo bem do mundo, um deles já está bem ferido e assustado com suas habilidades, como um simples robô consegue me atingir, um dos dragões está com um corte letal e deitar no chão morrendo com uma hemorragia, já o outro dragão ver aquilo como, ele era apenas mais um fraco dizendo isso o dragão pega umas das katanas e vai ao combate novamente contra você, sempre que as duas katanas se tocavam seu corpo ficava mais fraco, Zero já estava tremendo, com tamanha pressão você acaba perdendo seu braço esquerdo mas com isso lembra de tudo, seu treino, essa sala, e seus melhores golpes, mesmo sem um braço você conseguiu cortar a mão do dragão, a katana caia lentalmente e antes de tocar no chão você finaliza o segundo dragão com cortes profundos pelo corpo todo. Dois já foram falta um disse Zero após derrotar dois dragões e assim você acabar com a batalha sem um dos seus braços porém com uma nova katana a Phoenix Edge. vasculhando os corpos dos dragões você encontra a localização da base de produção das drogas e da localização do último dragão. Após algumas horas você retornar até o seu criador e contar sobre a batalha e a parca do seu braço, infelizmente por uma tecnologia de alta ponta não é possível arrumar, bom agora só lhe restar enfrentar o dragão ou desistir de tudo</p> <button onclick='carregarConteudo(desistir)'>Desistir</button> <button onclick='carregarConteudo(dragões)'>Desistir</button>";

var desistir = "<img src='imagens/desistiu.jgn' /> <h2>Fracasso/h2> <p>Zero ver o quão díficil é lutar contra os dragões, você lembra da cena de seus amigos mortos e diz a si mesmo que não vai conseguir vingar-los, lágrimas começa a sair de seus olhos mecánicos, você deixa seu passado para trás e segue sem rumo as ruas escuras da cidade até sua bateria descarregar.</p> <button onclick='carregarConteudo(KatanaZero)'>Tente novamente</button>";

var espadas1 = "<img src='imagens/espadas.png' /> <h2>Katanas/h2> <p>Então Zero decide que é melhor ir atrás das katanas, a localização não era muito longe da sua localização atual, ultilizando a base dos Kibuzi, você utiliza o mapa e as informações que a Snow te forneceram, todos se reuniram e partem para ir em busca das katanas. Após algumas horas vocês chegam no local, há diversos servintes dos dragões, vários guardas, seu equipe vai eliminando cada um aos poucos, alguns disparos atinjam sua equipe, mas nada muito grave, ao chegar na sala das espadas observar-se dois dragões esperando pela vossa chegada, estavamos esperando vocês disse o primeiro, vocês vão morrer agorar disse o segundo, todos na sala sacam suas katanas e uma batalha de cinco contra 2 se inicia, os dragões são rápidos e estão cortando cada vez mais os kibuzi, durante a batalha Snow e Zero estão concentrados em um dos dragões, enquanto o restante do esquadrão está focado no outro, em um bate de vento todos do esquadrão são decapitados, Dança do dragão foi o que o Primeiro Dragão bastante ferido disse, Snow bem furiosa segura sua katana com toda a força e parte o dragão no meio, Zero ao ver seu esquadrão todos mortos gera uma raiva dos dragões e concentra toda sua habilidade extraida das drogas e gera um cortex de corte em toda area, com isso os dois dragões presentes na sala morreram e a Katana de zero se partiu.Snow sai da sala dizendo: te espero lá fora, Zero apenas concordar e pega a Katana Phoenix Edge, ao sair da sala, Snow já estava andando no sentido da base e Zero apenas a acompanha. </p> <button onclick='carregarConteudo(desistir1)'>Desistir</button> <button onclick='carregarConteudo(dragões1)'>Enfrentar o dragão</button>";

var dragões = "<img src='imagens/dragões.jpg' /> <h2>Dragão</h2> <p>Então lá vai Zero, sozinho em uma noite fria indo direto a base, após um longo tempo andando você chegou no local e está tudo tão quieto, não há ninguém de vigia, ao abrir a porta está tudo escuro, ao entrar a porta logo atrás é fechada imediatamente e revela o último dragão em uma sala cheia de possíveis armadilhas, Seja bem vindo Zero, diz o dragão que matou seu melhor amigo Nier, os dois sacam suas espadas o brilho de duas láminas poderosas se encontram como um feixe dourado na sala toda, vejo que se aprimorou né diz o dragão, eu irei te matar aqui diz Zero gritando e correndo em direção ao dragão, láminas se encontram diversas vezes, eles estão o limite robô e humano exaustos de tanto balança a katana, ambos usuários das drogas vendo os movimentos de cada um. O dragão só não preveu a habilidade da Phoenix Edge, ao se ativada libera as chamas acumulada durante a batalha e assim queima inteiro o dragão e um pouco de sua pele robótica, Zero se ajoelha e percebe toda a jornada dele, todos os seus passos, sua jornada inteira, e ele nota que tem lotes de produção das drogas, você deseja mais poder ?</p> <button onclick='carregarConteudo(zerou)'>Tente novamente</button> <button onclick='carregarConteudo(acorda)'>Tente novamente</button>";

var dragões1 = "<img src='imagens/dragões.jpg' /> <h2>Dragão</h2> <p>ATENÇÃO MARIANA AQUI O ZERO TEM SUA AMIGA SNOW, ELA TA DEPRESSIVA POIS PERDEU TODOS SEUS AMIGOS, PORÉM SÃO DOIS GRANDES ESPADACHINS</p> <button onclick='carregarConteudo(KatanaZero)'>Tente novamente</button>";

var zerou = "<img src='imagens/dragões.jpg' /> <h2>Fim</h2> <p> </p> <button onclick='carregarConteudo(KatanaZero)'>Tente novamente</button>";

var poder = "<img src='imagens/acordou.jpg' /> <h2>Acordou ?</h2> <p>Você acorda em uma sala de terapeuta todo confuso e perdido, Você finalmente acordou, disse o terapeuta, estava começando a ficar </p><button onclick='carregarConteudo(KatanaZero)'>Tente novamente</button>";

var elemento = document.getElementById("conteudo");

function carregarConteudo(conteudo){
    elemento.innerHTML = conteudo;
}

function mudarEstilos()  {
    //Dentro dessa função, escreva o codigo para alterar o estilo do elemento com o id "text". 
    //A cor do texto deve ser verde, o tamanho do texto deve ser 15px e a fonte escolhida deve ser Arial;
    //Escreva sua resposta no espaço abaixo.  
    //Um exemplo de alteração de estilos por javascript: text.style.fontFamily = "Comic Sans MS";
    // font-family: banana;
    
    text.style.fontFamily = "Arial";
    text.style.fontSize = "15px ";
    text.style.color = "green";
    text.style.padding = "20";
    text.style.backgroundColor = "#333";
    text.style.textAlign 
}

carregarConteudo(KatanaZero)


var checkbox = document.getElementById("ChangeTheme"); 

if (sessionStorage.getItem("mode") == "dark") {
  darkmode(); 
} else {
  nodark(); 
}

checkbox.addEventListener("change", function() {
  if (checkbox.checked) {
    darkmode();
  } else {
    nodark(); 
  }
});

function darkmode() {
  document.body.classList.add("dark-mode"); 
  checkbox.checked = true; 
  sessionStorage.setItem("mode", "dark"); 
}

function nodark() {
  document.body.classList.remove("dark-mode"); 
  checkbox.checked = false; 
  sessionStorage.setItem("mode", "light");
}