var Começo = `<img src='imagens/atv.png' /> <h2>Atividade Proa</h2> <p> Ativida proposta pelo professor Gabriel Augusto (vulgo Gabriel Lindo Augusto) durante o Instituto Proa, o objetivo da atividade é criar um jogo utilizando as tecnologias de HTML e CSS e a linguagem de programação JavaScript. Atividade feita pelos Alunos: Mariana Oliveira e Luan Fernando. Informe o nome do personagem, seja criativo e diverta-se <3 </p> <div class="btn"> <button onclick='carregarConteudo(KatanaZero)'>Começar</button> </div>`;

let nome = prompt('Digite o nome do personagem para o jogo: ');

var KatanaZero = `<img src='imagens/begging.png' /> <h2>Katana Zero</h2> <p>Em uma cidade escura e chuvosa, em um mundo controlado pelo governo e dominado por guerras, o governo desenvolveu uma droga, uma droga capaz de se autoaprimorar e utilizaram pra desenvolver um exército para dominar terras e consquistar o planeta. E assim acorda ${nome}, um robô muito semelhante a um humano e com a marca do exercíto, com o braço enferrujado e com peças faltando, ${nome} acorda perto de um posto de gasolina abandonado, ele não se lembra de nada, apenas de seu nome, ao seu lado a sua katana escrita com seu nome, ${nome} percebe que está danificado e sem carga assim lembra que é um robô procurado pelo governo. ${nome} vai até o posto e encontra algumas peças antigas de robô e uma bateria antiga, fora do modelo avançado do seu corpo, ao ver as peças se lembra do seu antigo amigo de guerra, o Nier, um amigo robô na qual foi desenvolvido junto com ele, ${nome} deseja encontra Nier para saber sobre seu passado obscuro. Então ${nome} começa a se autoconsertar com as peças antigas e deseja muito ir atrás do Nier e vai em buscar de respostas na cidade mais próxima..</p> <div class="btn"> <button onclick='carregarConteudo(EmBuscaDeNier)'>Ir em buscar de Nier</button> <button onclick='carregarConteudo(Bar)'>Ir para o bar</button> </div>`;

var Bar = `<img src='imagens/bar.png' /> <h2>Bar</h2> <p>${nome} não está muito afim de saber o que aconteceu nem sobre o que está acontecendo, ele apenas notou que tem alguns trocados no balcão do posto e decide ir tomar breja, afinal ele é apenas um robô sem memória e com peças velhas, por que não ir para um bar? Pois então é isso que ${nome} fez, ele partiu deixando seu passado para trás, após algumas horas finalmente achou um bar, usou seus trocados e bebeu até se descarregar, acho que a bateria que ele encontrou não estava tão carregada assim...</p> <div class="btn"> <button onclick='carregarConteudo(KatanaZero)'>Tente novamente</button> </div>`;

var EmBuscaDeNier = `<img src='imagens/city.png' /> <h2>Cidade</h2>  <p>${nome} caminha por horas até chegar na cidade, onde sobe um grande prédio e encontra um gato preto e meio magro, já é de noite, as ruas estão vazias ${nome} observa os cartezes de diversos robôs procurados, entre eles, havia ${nome} e Nier, ${nome} leva o cartaz e vai até o armazem secretos dos robôs. Ao chegar próximo do armazem de robôs, ele já nota o excesso de óleo nas ruas e nas paredes, marcas de mão e pés, tudo em um formato semelhante as da técnologia dele, ${nome} entra no armazem e encontra diversos robôs do esquadrão dele mortos, estraçalhados e decapitados, Quem fez isso, disse ${nome} com enjoo e espantado, ele escuta uma voz, é o Nier, ele está sem suas pernas e com uma katana escrito Dragão no peito pendurando o Nier na parede dos fundos, ${nome} está assustado, o esquadrão mais forte está todo morto, disse ${nome}, nier enquanto estava perdendo sua consciência disse : Aonde você estava ${nome}, ${nome} conta que não se lembra de nada e que acordou no meio do nada, Nier começa a explicar, O governo desenvolver um esquadrão poderoso para eliminar todos os robôs, eles são chamados de Dragões, eles são poderosos e utilizaram a droga como nós, ${nome} pergunta sobre a droga, Nier conta que os robôs foram um projeto do governo com a utilização das drogas pra derrotamos outros países, porém foi um fracasso, e agora querem  eliminar todos os robôs, talvez você seja o último disse Nier para ${nome}, ao dizer isso Nier se despedir de ${nome} e aponta para a porta dos fundos, onde há os registros de todos os abrigos robóticos, equipamentos e a localização do criador dos robôs. ${nome} pensa em duas alternativas, ir atrás do criador ou se aprimorar para enfrentar os Dragões. </p> <div class="btn"> <button onclick='carregarConteudo(Criador)'>Ir atrás do criador</button> <button onclick='carregarConteudo(Aprimorar)'>Ir até os Dragões</button> </div>`;

var Criador = `<img src='imagens/fuga.png' />  <h2>Criador</h2> <p>${nome} deseja ir atrás de respostas, então ele vasculha os documentos e acha um mapa mostrando onde está o criador dos robôs, ${nome} passa mais uma vez pela cena de seus amigos mortos e segue a porta da frente, ver seus companheiros mortos e sentir aquele cheiro o abalou, ele pode ser um robô porém, ele ainda tem sentimentos pelos seus colegas antes de ir a porta, ele grava a sua katana no chão e jura aos colegas mortos que trará a vingança a todos, de joelhos ${nome} foca na cena tenta adquirir seu poder de volta mas a droga já não está mais causando efeitos, ele precisa se recarregar. ${nome} pega sua katana do chão e vai a saída e encontra vários carros e polícias cercando de todos os lados, o governo o achou, nos prédios há três guerreios com katanas e simbolos de dragões na roupa, um deles está cheio de óleo, a polícia solicita-o que jogue a arma no chão, ${nome} está irritado e começa a matar os polícias, um deles o acerta, você ja era, diz um dos Dragões, mesmo ferido ${nome} derruba todos os polícias porém ao matar o último guarda, um dragão o acerta no peito, você foi o mais fraco, disse o dragão que estava com as roupa cheia de óleo, eu matei seus amigos e agora você se unirá com eles. ${nome} está morto </p> <div class="btn"> <button onclick='carregarConteudo(KatanaZero)'>Tente de novo</button> </div>`;

var Aprimorar = `<img src='imagens/poderes.png' />  <h2>Aprimoramentos</h2> <p>${nome} vasculha a sala inteira, ele encontra peças do modelo mais avançado que há, dentro de uma caixa que havia as peças ele acha uma carga grande da droga do governo, com isso poderei recuperar meus poderes disse ${nome}, ele fica de joelho e concentra todo o seu corpo para lembrar de seus poderes, assim ele ira recuperar seu auto reflexo, deixando capaz de refletir alguns projéteis, em uma das caixas havia uma chave escrito fundo nela, é a chave dos fundo, disse  ${nome}, então lá foi ele ao fundos. Indo aos fundos alguns polícias que estavam aguardando ele na porta começaram a entrar, ${nome} sacou sua katana e começaram os disparos, ${nome} ativou seu reflexo e viu aquela oportunidade como uma ótima forma para treinar e foi para cima dos guardas, refletia suas balas como nunca, conseguia ver todos os trajetos e anglos, eliminou todos, mas sabia que mais guardas iriam vir, foi depressa a porta dos fundos, chegando lá encontrou uma porta enorme de ferro, parecia um bunker, utilizou a chave com delicadeza para não quebrar a chave, ABRIU ele disse, entrou correndo e fechou a porta, em seguida ouviu uma voz dizendo finalmente você apareceu, ${nome} olhou para trás e viu que quem estava lá na frente dele era ninguém menos que seu criador. Ele explica que o esquadrão que está morto lá na frente morreram protegendo ele, e diz que os dragões roubaram a fórmula da droga e estão fabricando e fazendo soldados para eles mesmo, aqueles não são polícias, são recrutas dos dragões, diz o criador. Enquanto isso os dragões estão tentando quebrar a porta,o criador quer que você corra pra longe, ${nome} tem duas escolhas ficar e tentar proteger ou correr </p> <div class="btn"> <button onclick='carregarConteudo(Correr)'>Correr</button> <button onclick='carregarConteudo(Proteger)'>Proteger</button> </div>`;

var Proteger = `<img src='imagens/lab.png' />  <h2>Proteger</h2> <p> ${nome} decide proteger seu criador, após tanto tempo sem achar seu mestre, quando finalmente o encontra partir assim? juntos eles criam uma barreira na porta para ganhar tempo, com isso eles vão a porta dos fundos, precisamos achar um local seguro disse ${nome} ao criador, eles vão por cimas dos prédios atrás de um abrigo longe do alcance dos dragões. Após um longo tempo acham uma sala bem longe do centro da cidade em um antigo quarto do criador, é aqui o local, disse o criador, então o mestre começa a explicar que o dragões dominaram o governo e decidiram matar todos quem ligação com os robôs, com isso ${nome} já estava com a bateria descarregando, então o criador colocou ele em uma capsula para carregar e fazer alguns ajustes finais no corpo de ${nome}. Um dia se passou, ${nome} acorda e está se sentido como nunca se sentiu antes, mais rápido, mais forte, mais leve. Fiz bem em proteger você, disse ${nome} ao criador, agora só falta uma coisa uma katana aprimorada, os dragões são fortes porém tem pontos fracos, todos podem facilmente ser derrotados com a Phoenix Edge, uma katana especial criada por um antigo mestre do corte, e guardada bem no centro da cidade. ${nome} tem duas escolhas enfrentar os dragões ou ir em busca da katana</p> <div class="btn"> <button onclick='carregarConteudo(dragões)'>Enfrentar os dragões</button> <button onclick='carregarConteudo(espadas)'>Ir em busca da katana</button> </div>`;

var Correr = `<img src='imagens/run.png' />  <h2>Correr</h2> <p>Correr as vezes pode não ser a melhor escolha, mas talvez nesse situação pode ser a melhor alternativa, ${nome} corre para as portas do fundo e enquanto corre, escuta os gritos de seu criador sendo cortado diversas vezes pelos dragões, agora sem rumo ${nome} está vagando por informações, ele se questiona diversas vezes, será que há outro robô ainda ? será que há alguém querendo derrubar o governo? por que o governo quer destruiu algo que eles criaram ? vagando pelas ruas, entrou em um bar em um bairro bem obscuro, havia uma mulher com uma katana e uma roupa azul, ela se aproxima do ${nome} e diz sussurando: finalmente apareceu estava tentando falar com você a dias, ${nome} confuso apenas diz sussurando: Quem é você? Eu perdi minha memória eu acordei no meio do nada, Então ela o convida para uma mesa e conta sobre a relação deles, somos uma equipe formada pelos sobreviventes da guerra, os Kibuzi, meu codinome é Snow disse ela. ${nome} começa a lembrar do grande esquadrão que ele havia formado, como pude esquecer dos Kibuzi, passam o dia conversando e vão pelas sombras até o abrigo. Kibuzi são no total 4 membros e usuários das katanas, eles buscam destruir os dragões e também são guerreios que utilizam a droga. ${nome} aproveita para utilizar mais da droga e foca a voltar suas habilidades, com isso sua percepção e campo de visão aumentam. Os kibuzi sugerem pegar umas das cinco gold katanas, pois são katanas poderosas e cada uma com uma habilidade diferente. Agora você decide, ir atrás dos dragões ou ir em busca das espadas</p> <div class="btn"> <button onclick='carregarConteudo(espadas1)'>Ir em busca das katanas</button> <button onclick='carregarConteudo(dragões1)'>Ir atrás dos dragões</button> </div>`;

var espadas = `<img src='imagens/espadas.png' /> <h2>Katanas</h2> <p>Então ${nome} decide que é melhor ir atrás das katanas, a localização não era muito longe da sua localização atual, utilizando seu novo corpo, ${nome} acha a localização e parti ao anoitecer, chegando lá você se depara com diversos guardas na entrada, mas ${nome} está lidando está situação com uma facilidade é como se estiver cortando folhas e repelindo todas os projéteis, nada o atingia, chegando perto das espadas ele encontrou dois dos três dragões, sabiamos que estaria aqui disse um, você ira morrer aqui disse o outro, a sua frente há uma luta díficil um contra dois, porém nada além do seu nível, não há formas de correr ou se proteger, então você vai a frente no combate, os dois dragões te acompanham, ${nome} esquiva de vários golpes mas ainda sim é atingido, uma batalha de agilidade e força pelo bem do mundo, um deles já está bem ferido e assustado com suas habilidades, como um simples robô consegue me atingir, um dos dragões está com um corte letal e deita no chão morrendo com uma hemorragia, já o outro dragão ve aquilo como, ele era apenas mais um fracote dizendo isso o dragão pega umas das katanas e vai ao combate novamente contra você, sempre que as duas katanas se tocavam seu corpo ficava mais fraco, ${nome} já estava tremendo, com tamanha pressão você acaba perdendo seu braço esquerdo mas com isso lembra de tudo, seu treino, essa sala, e seus melhores golpes, mesmo sem um braço você conseguiu cortar a mão do dragão, a katana caia lentalmente e antes de tocar no chão você finaliza o segundo dragão com cortes profundos pelo corpo todo. Dois já foram falta um disse ${nome} após derrotar dois dragões e assim você acabar com a batalha sem um dos seus braços porém com uma nova katana a Phoenix Edge. vasculhando os corpos dos dragões você encontra a localização da base de produção das drogas e da localização do último dragão. Após algumas horas você retornar até o seu criador e conta sobre a batalha e a parca do seu braço, infelizmente por uma tecnologia de alta ponta não é possível arrumar, bom agora só lhe restar enfrentar o dragão ou desistir de tudo</p> <div class="btn"> <button onclick='carregarConteudo(desistir)'>Desistir</button> <button onclick='carregarConteudo(dragões)'>Enfrentar dragões</button> </div>`;

var desistir = `<img src='imagens/desistiu.png' /> <h2>Fracasso</h2> <p>${nome} ver o quão díficil é lutar contra os dragões, você lembra da cena de seus amigos mortos e diz a si mesmo que não vai conseguir vingar-los, lágrimas começa a sair de seus olhos mecánicos, você deixa seu passado para trás e segue sem rumo as ruas escuras da cidade até sua bateria descarregar.</p> <div class="btn"> <button onclick='carregarConteudo(KatanaZero)'>Tente novamente</button> </div>`;

var espadas1 = `<img src='imagens/espadas.png' /> <h2>Katanas</h2> <p>Então ${nome} decide que é melhor ir atrás das katanas, a localização não era muito longe da sua localização atual, ultilizando a base dos Kibuzi, você utiliza o mapa e as informações que a Snow te forneceram, todos se reuniram e partem para ir em busca das katanas. Após algumas horas vocês chegam no local, há diversos servintes dos dragões, vários guardas, seu equipe vai eliminando cada um aos poucos, alguns disparos atinjam sua equipe, mas nada muito grave, ao chegar na sala das espadas observar-se dois dragões esperando pela vossa chegada, estavamos esperando vocês disse o primeiro, vocês vão morrer agorar disse o segundo, todos na sala sacam suas katanas e uma batalha de cinco contra 2 se inicia, os dragões são rápidos e estão cortando cada vez mais os kibuzi, durante a batalha Snow e ${nome} estão concentrados em um dos dragões, enquanto o restante do esquadrão está focado no outro, em um bate de vento todos do esquadrão são decapitados, Dança do dragão foi o que o Primeiro Dragão bastante ferido disse, Snow bem furiosa segura sua katana com toda a força e parte o dragão no meio, ${nome} ao ver seu esquadrão todos mortos gera uma raiva dos dragões e concentra toda sua habilidade extraida das drogas e gera um cortex de corte em toda area, com isso os dois dragões presentes na sala morreram e a Katana de ${nome} se partiu.Snow sai da sala dizendo: te espero lá fora, ${nome} apenas concordar e pega a Katana Phoenix Edge, ao sair da sala, Snow já estava andando no sentido da base e ${nome} apenas a acompanha. </p> <div class="btn"> <button onclick='carregarConteudo(desistir1)'>Desistir</button> <button onclick='carregarConteudo(dragões1)'>Enfrentar o dragão</button> </div>`;

var dragões = `<img src='imagens/dragão.png' /> <h2>Dragão</h2> <p>Então lá vai ${nome}, sozinho em uma noite fria indo direto a base, após um longo tempo andando você chegou no local e está tudo tão quieto, não há ninguém de vigia, ao abrir a porta está tudo escuro, ao entrar a porta logo atrás é fechada imediatamente e revela o último dragão em uma sala cheia de possíveis armadilhas, Seja bem vindo ${nome}, diz o dragão que matou seu melhor amigo Nier, os dois sacam suas espadas o brilho de duas láminas poderosas se encontram como um feixe dourado na sala toda, vejo que se aprimorou né diz o dragão, eu irei te matar aqui diz ${nome} gritando e correndo em direção ao dragão, láminas se encontram diversas vezes, eles estão no limite, robô e humano exaustos de tanto balançar a katana, ambos usuários das drogas vendo os movimentos de cada um. O dragão só não preveu a habilidade da Phoenix Edge, ao ser ativada libera as chamas acumuladas durante a batalha e assim queima inteiro o dragão e um pouco de sua pele robótica, ${nome} se ajoelha e percebe toda a jornada dele, todos os seus passos, sua jornada inteira, e ele nota que tem lotes de produção das drogas, você deseja mais poder ?</p> <div class="btn"> <button onclick='carregarConteudo(Zerou)'>Fim?</button> <button onclick='carregarConteudo(poder)'>Mais poder</button> </div>`;

var dragões1 = `<img src='imagens/dragão.png' /> <h2>Dragão</h2> <p>Então ${nome} e Snow estão seguindo rumo a base, após um logo tempo andando na chuva, chegaram em um local quieto e simplesmente ninguém de vigia, portas destrancas, ${nome} ao abrir a porta ser depara com o dragão sentado em uma cadeira em uma sala toda metálica. seja bem vindo diz o dragão gargalhando, Você lembra que eu matei seus amigos ? disse o dragão gargalhando e saciando um belo vinho, Snow saca sua katana e vai ao combate sem mais nem menos ${nome} a acompanhar, Snow é atigida diversas vezes com cortes leves, ${nome} toma frente do combate e com toda sua raiva acumulada e exala cortes jamais vistos por usuários da Katana, uma pressão de vento se criar a cada balança da katana, Snow no chão fica admirando, aquela velocidade, aquela força, aquilo não era apenas ${nome}, era tudo que ele passou, todos que viu ou ouviu morrerem, toda dor que ele sentiu, apesar de ser um robô ele ainda tinha sentimentos, os amigos, o criador, seu esquadrão e sua cidade, tudo isso havia acabado quando ${nome} corta o pescoço fora do último dragão, sua vingança foi feita, a liberdade foi restaurada, agora posso levantar a cabeça e sorrir novamente disse ${nome} chorando a Snow, então conseguimos disse Snow chorando no chão, ela se levanta e se abraçam tudo foi superado, passam alguns minutos ainda na sala até que ${nome} nota que tem alguns lotes de produção das drogas, você deseja mais poder ? ou já está satisfeito ? </p> <div class="btn"> <button onclick='carregarConteudo(poder)'>Deseja mais poder ?</button> <button onclick='carregarConteudo(Zerou)'>Fim ?</button></div>`

var Zerou = `<img src='imagens/arigato.png' /> <h2>Fim</h2> <p>Sim, chegou ao fim, toda sua jornana passa pelos seus olhos, tudo foi tão rápido cheguei aonde não esperava chegar e conseguir, venci os dragões, liberei o estado do mal dos dragões, finalmente o peso dos meus colegas está livre, me sinto mais leve, superei todos os meus erros e finalmente posso seguir em frente disse ${nome} chorando com sua katana na mão...</p> <div class="btn"> <button onclick='carregarConteudo(jogo)'>Fim de jogo</button> </div>`;

var poder = `<img src='imagens/acordou.png' /> <h2>Acordou ?</h2> <p>Você acorda em uma sala de um psícologo todo confuso e perdido, Você finalmente acordou, disse o psícologo, estava começando a ficar preocupado com sua saúde mental, você voltou a ter pesadelos sobre robôs ? Aah vou ter recomendar o mesmo remédio da semana passada assim podemos ter algum resultado parecido ao do semestre passado, disse o psícologo, enquanto isso ${nome} apenas se levanta e lembra que é um amante de cosplay de espadachim e amante do jogo KatanaZero. Obrigado por jogar <3 ! </p> <div class="btn"> <button onclick='carregarConteudo(jogo)'>Fim </button> </div>`;

var jogo = `<img src='imagens/katana.png' /> <h2>Obrigado por jogar</h2> <p>Esse jogo foi apenas uma atividade do Instituto Proa, as imagens foram tiradas do jogo Katana Zero, você pode comprar na Steam por apenas 28,90 Reais. Recomendamos.</p> <div class="btn"> <button onclick='carregarConteudo(KatanaZero)'>Jogar novamente ?</button> </div>`;






var elemento = document.getElementById("conteudo");

function carregarConteudo(conteudo){
    elemento.innerHTML = conteudo;
}

function mudarEstilos()  {
    text.style.fontFamily = "Arial";
    text.style.fontSize = "15px ";
    text.style.color = "green";
    text.style.padding = "20";
    text.style.backgroundColor = "#333";
}

carregarConteudo(Começo);


var checkbox = document.getElementById("ChangeTheme"); 

if (sessionStorage.getItem("mode") == "dark") {
  darkmode(); 
} else {
  nodark(); 
}

checkbox.addEventListener("change", function() {
  if (checkbox.checked) {
    darkmode();
  } else {
    nodark(); 
  }
});

function darkmode() {
  document.body.classList.add("dark-mode"); 
  checkbox.checked = true; 
  sessionStorage.setItem("mode", "dark"); 
}

function nodark() {
  document.body.classList.remove("dark-mode"); 
  checkbox.checked = false; 
  sessionStorage.setItem("mode", "light");
}

//Atividade feita por Mariana Oliveira e Luan Fernando 27/09/2021.